name: Test results
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-report:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: dorny/test-reporter@v2
        with:
          name: Test results
          artifact: test-results
          path: "**/*.trx"
          reporter: dotnet-trx
          list-tests: failed
          fail-on-error: true