name: Test results
on:
  workflow_run:
    workflows:
      - SonarCloud
    types:
      - completed

jobs:
  report:
    runs-on: windows-latest
    steps:
      - uses: dorny/test-reporter@v2
        with:
          name: Test results
          artifact: test-results
          path: "**/*.trx"
          reporter: dotnet-trx
          fail-on-error: true